// components/UserDialog.vue
<script setup lang="ts">
import Button from '@/components/ui/Button.vue'
import Checkbox from '@/components/ui/Checkbox.vue'
import Dialog from '@/components/ui/Dialog.vue'
import Input from '@/components/ui/Input.vue'
import Label from '@/components/ui/Label.vue'
import { toast } from 'vue-sonner'

interface UserData {
  id?: string
  idNumber: string
  firstNames: string
  lastNames: string
  phone: string | null
  address: string | null
  email: string | null
  baptismDate: string | null
  whatsapp: boolean
  created_at?: string
}

interface UserDialogProps {
  isOpen: boolean
  user: UserData | null
}

const props = defineProps<UserDialogProps>()
const emit = defineEmits<{ close: []; save: [] }>()

const isEditing = computed(() => !!props.user)
const isLoading = ref(false)
const formData = reactive({
  idNumber: '',
  firstNames: '',
  lastNames: '',
  phone: '',
  address: '',
  email: '',
  baptismDate: '',
  whatsapp: false,
})
const errors = reactive<Record<string, string>>({})

// Inicializar formulario cuando cambie el usuario
watch(
  () => props.user,
  newUser => {
    if (newUser) {
      Object.assign(formData, {
        idNumber: newUser.idNumber || '',
        firstNames: newUser.firstNames || '',
        lastNames: newUser.lastNames || '',
        phone: newUser.phone || '',
        address: newUser.address || '',
        email: newUser.email || '',
        baptismDate: newUser.baptismDate
          ? new Date(newUser.baptismDate).toISOString().split('T')[0]
          : '',
        whatsapp: newUser.whatsapp || false,
      })
    } else {
      // Reset form
      Object.assign(formData, {
        idNumber: '',
        firstNames: '',
        lastNames: '',
        phone: '',
        address: '',
        email: '',
        baptismDate: '',
        whatsapp: false,
      })
    }
    // Limpiar errores
    Object.keys(errors).forEach(key => delete errors[key])
  },
  { immediate: true }
)

const handleChange = (field: keyof typeof formData, value: any) => {
  formData[field] = value
  if (errors[field]) {
    delete errors[field]
  }
}

const validateForm = () => {
  const newErrors: Record<string, string> = {}

  if (!formData.idNumber.trim()) {
    newErrors.idNumber = 'La cédula es obligatoria'
  } else if (!/^\d+$/.test(formData.idNumber)) {
    newErrors.idNumber = 'La cédula debe contener solo números'
  }

  if (!formData.firstNames.trim()) {
    newErrors.firstNames = 'El nombre es obligatorio'
  }

  if (!formData.lastNames.trim()) {
    newErrors.lastNames = 'El apellido es obligatorio'
  }

  if (formData.email && !/^\S+@\S+\.\S+$/.test(formData.email)) {
    newErrors.email = 'El correo electrónico no es válido'
  }

  Object.keys(newErrors).forEach(key => {
    errors[key] = newErrors[key]
  })

  return Object.keys(newErrors).length === 0
}

const handleSubmit = async () => {
  if (!validateForm()) {
    return
  }

  isLoading.value = true

  try {
    const endpoint = isEditing.value
      ? `/api/admin/users/${props.user?.id}`
      : '/api/admin/users'

    const method = isEditing.value ? 'PUT' : 'POST'

    const response = await $fetch(endpoint, {
      method,
      body: {
        ...formData,
        baptismDate: formData.baptismDate || null,
        phone: formData.phone || null,
        address: formData.address || null,
        email: formData.email || null,
      },
    })

    toast.success(isEditing.value ? 'Usuario actualizado' : 'Usuario creado')
    emit('save')
    emit('close')
  } catch (error: any) {
    console.error('Error al guardar usuario:', error)
    errors.form = error?.data?.error || 'Ocurrió un error al guardar el usuario'
    toast.error(errors.form)
  } finally {
    isLoading.value = false
  }
}

const handleClose = () => {
  emit('close')
}
</script>

<template>
  <Dialog :open="isOpen" @close="handleClose">
    <div class="sm:max-w-md">
      <div class="mb-4">
        <h2 class="text-lg font-semibold">
          {{ isEditing ? 'Editar Usuario' : 'Nuevo Usuario' }}
        </h2>
      </div>

      <form @submit.prevent="handleSubmit" class="space-y-4">
        <div class="grid gap-4">
          <div class="grid gap-2">
            <Label for="idNumber">Cédula *</Label>
            <Input
              id="idNumber"
              v-model="formData.idNumber"
              @input="handleChange('idNumber', $event.target.value)"
              :disabled="isLoading"
            />
            <span v-if="errors.idNumber" class="text-sm text-red-500">
              {{ errors.idNumber }}
            </span>
          </div>

          <div class="grid gap-2 md:grid-cols-2">
            <div>
              <Label for="firstNames">Nombres *</Label>
              <Input
                id="firstNames"
                v-model="formData.firstNames"
                @input="handleChange('firstNames', $event.target.value)"
                :disabled="isLoading"
              />
              <span v-if="errors.firstNames" class="text-sm text-red-500">
                {{ errors.firstNames }}
              </span>
            </div>
            <div>
              <Label for="lastNames">Apellidos *</Label>
              <Input
                id="lastNames"
                v-model="formData.lastNames"
                @input="handleChange('lastNames', $event.target.value)"
                :disabled="isLoading"
              />
              <span v-if="errors.lastNames" class="text-sm text-red-500">
                {{ errors.lastNames }}
              </span>
            </div>
          </div>

          <div class="grid gap-2 md:grid-cols-2">
            <div>
              <Label for="email">Correo</Label>
              <Input
                id="email"
                v-model="formData.email"
                @input="handleChange('email', $event.target.value)"
                type="email"
                :disabled="isLoading"
              />
              <span v-if="errors.email" class="text-sm text-red-500">
                {{ errors.email }}
              </span>
            </div>
            <div>
              <Label for="phone">Teléfono</Label>
              <Input
                id="phone"
                v-model="formData.phone"
                @input="handleChange('phone', $event.target.value)"
                :disabled="isLoading"
              />
            </div>
          </div>

          <div class="grid gap-2">
            <Label for="address">Dirección</Label>
            <Input
              id="address"
              v-model="formData.address"
              @input="handleChange('address', $event.target.value)"
              :disabled="isLoading"
            />
          </div>

          <div class="grid gap-2">
            <Label for="baptismDate">Fecha Bautizo</Label>
            <Input
              id="baptismDate"
              v-model="formData.baptismDate"
              @input="handleChange('baptismDate', $event.target.value)"
              type="date"
              :disabled="isLoading"
            />
          </div>

          <div class="flex items-center gap-2">
            <Checkbox
              id="whatsapp"
              v-model="formData.whatsapp"
              @update:checked="handleChange('whatsapp', $event)"
              :disabled="isLoading"
            />
            <Label for="whatsapp" class="text-sm font-normal">
              Tiene WhatsApp
            </Label>
          </div>

          <div v-if="errors.form" class="text-center text-sm text-red-500">
            {{ errors.form }}
          </div>
        </div>

        <div class="flex justify-end gap-3">
          <Button
            type="button"
            variant="outline"
            @click="handleClose"
            :disabled="isLoading"
          >
            Cancelar
          </Button>
          <Button type="submit" :disabled="isLoading">
            <span v-if="isLoading" class="flex items-center gap-2">
              <div
                class="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent"
              ></div>
              Guardando...
            </span>
            <span v-else>Guardar</span>
          </Button>
        </div>
      </form>
    </div>
  </Dialog>
</template>

// components/usuarios/user-dialog.tsx
"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Loader2 } from "lucide-react";
import { format } from "date-fns";
import { es } from "date-fns/locale";

type UserProps = {
  id: string;
  cedula: string;
  nombres: string;
  apellidos: string;
  telefono: string | null;
  direccion: string | null;
  correo: string | null;
  fecha_bautizo: string | null;
  whatsapp: boolean;
  created_at: string;
};

type UserDialogProps = {
  isOpen: boolean;
  onClose: () => void;
  user: UserProps | null;
  onSave: () => void;
};

export function UserDialog({ isOpen, onClose, user, onSave }: UserDialogProps) {
  const isEditing = !!user;
  const [isLoading, setIsLoading] = useState(false);
  const [formData, setFormData] = useState({
    cedula: user?.cedula || "",
    nombres: user?.nombres || "",
    apellidos: user?.apellidos || "",
    telefono: user?.telefono || "",
    direccion: user?.direccion || "",
    correo: user?.correo || "",
    fecha_bautizo: user?.fecha_bautizo || null,
    whatsapp: user?.whatsapp || false,
  });
  const [errors, setErrors] = useState<Record<string, string>>({});

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    if (errors[name]) {
      setErrors((prev) => {
        const newErrors = { ...prev };
        delete newErrors[name];
        return newErrors;
      });
    }
  };

  const handleCheckboxChange = (checked: boolean) => {
    setFormData((prev) => ({ ...prev, whatsapp: checked }));
  };

  const handleDateChange = (value: string | null) => {
    setFormData((prev) => ({ ...prev, fecha_bautizo: value }));
  };

  const validateForm = () => {
    const newErrors: Record<string, string> = {};

    if (!formData.cedula.trim()) {
      newErrors.cedula = "La cédula es obligatoria";
    } else if (!/^\d+$/.test(formData.cedula)) {
      newErrors.cedula = "La cédula debe contener solo números";
    }

    if (!formData.nombres.trim()) {
      newErrors.nombres = "El nombre es obligatorio";
    }

    if (!formData.apellidos.trim()) {
      newErrors.apellidos = "El apellido es obligatorio";
    }

    if (formData.correo && !/^\S+@\S+\.\S+$/.test(formData.correo)) {
      newErrors.correo = "El correo electrónico no es válido";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setIsLoading(true);

    try {
      const endpoint = isEditing
        ? `/api/admin/users/${user.id}`
        : "/api/admin/users";

      const method = isEditing ? "PUT" : "POST";

      const response = await fetch(endpoint, {
        method,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.message || "Error al guardar el usuario");
      }

      onSave();
    } catch (error) {
      console.error("Error al guardar usuario:", error);
      setErrors((prev) => ({
        ...prev,
        form: "Ocurrió un error al guardar el usuario",
      }));
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>
            {isEditing ? "Editar Usuario" : "Nuevo Usuario"}
          </DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="cedula" className="text-right">
                Cédula*
              </Label>
              <Input
                id="cedula"
                name="cedula"
                value={formData.cedula}
                onChange={handleChange}
                className="col-span-3"
                disabled={isLoading}
              />
              {errors.cedula && (
                <p className="text-red-500 text-sm col-span-3 col-start-2">
                  {errors.cedula}
                </p>
              )}
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="nombres" className="text-right">
                Nombres*
              </Label>
              <Input
                id="nombres"
                name="nombres"
                value={formData.nombres}
                onChange={handleChange}
                className="col-span-3"
                disabled={isLoading}
              />
              {errors.nombres && (
                <p className="text-red-500 text-sm col-span-3 col-start-2">
                  {errors.nombres}
                </p>
              )}
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="apellidos" className="text-right">
                Apellidos*
              </Label>
              <Input
                id="apellidos"
                name="apellidos"
                value={formData.apellidos}
                onChange={handleChange}
                className="col-span-3"
                disabled={isLoading}
              />
              {errors.apellidos && (
                <p className="text-red-500 text-sm col-span-3 col-start-2">
                  {errors.apellidos}
                </p>
              )}
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="correo" className="text-right">
                Correo
              </Label>
              <Input
                id="correo"
                name="correo"
                type="email"
                value={formData.correo || ""}
                onChange={handleChange}
                className="col-span-3"
                disabled={isLoading}
              />
              {errors.correo && (
                <p className="text-red-500 text-sm col-span-3 col-start-2">
                  {errors.correo}
                </p>
              )}
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="telefono" className="text-right">
                Teléfono
              </Label>
              <Input
                id="telefono"
                name="telefono"
                value={formData.telefono || ""}
                onChange={handleChange}
                className="col-span-3"
                disabled={isLoading}
              />
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="direccion" className="text-right">
                Dirección
              </Label>
              <Input
                id="direccion"
                name="direccion"
                value={formData.direccion || ""}
                onChange={handleChange}
                className="col-span-3"
                disabled={isLoading}
              />
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="fecha_bautizo" className="text-right">
                Fecha Bautizo
              </Label>
              <Input
                id="fecha_bautizo"
                name="fecha_bautizo"
                type="date"
                value={
                  formData.fecha_bautizo
                    ? new Date(formData.fecha_bautizo)
                        .toISOString()
                        .split("T")[0]
                    : ""
                }
                onChange={(e) => handleDateChange(e.target.value || null)}
                className="col-span-3"
                disabled={isLoading}
              />
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="whatsapp" className="text-right">
                WhatsApp
              </Label>
              <div className="flex items-center space-x-2 col-span-3">
                <Checkbox
                  id="whatsapp"
                  checked={formData.whatsapp}
                  onCheckedChange={handleCheckboxChange}
                  disabled={isLoading}
                />
                <Label htmlFor="whatsapp" className="text-sm font-normal">
                  Tiene WhatsApp
                </Label>
              </div>
            </div>

            {errors.form && (
              <p className="text-red-500 text-sm text-center">{errors.form}</p>
            )}
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={onClose}
              disabled={isLoading}
            >
              Cancelar
            </Button>
            <Button type="submit" disabled={isLoading}>
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Guardando...
                </>
              ) : (
                "Guardar"
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
