// components/ui/Breadcrumb.vue
<script setup lang="ts">
const props = defineProps<{ items: { label: string; href?: string }[] }>()
</script>
<template>
  <nav class="text-muted-foreground text-sm" aria-label="Breadcrumb">
    <ol class="flex items-center gap-2">
      <li
        v-for="(it, idx) in props.items"
        :key="idx"
        class="flex items-center gap-2"
      >
        <NuxtLink v-if="it.href" :to="it.href" class="hover:underline">{{
          it.label
        }}</NuxtLink>
        <span v-else class="text-foreground">{{ it.label }}</span>
        <span v-if="idx < props.items.length - 1" class="opacity-60">/</span>
      </li>
    </ol>
  </nav>
</template>

// components/ui/breadcrumb.tsx
"use client";

import Link from "next/link";
import { ChevronRight } from "lucide-react";

interface BreadcrumbItem {
  label: string;
  href: string;
}

interface BreadcrumbProps {
  items: BreadcrumbItem[];
}

export function Breadcrumb({ items }: BreadcrumbProps) {
  return (
    <nav className="flex" aria-label="Breadcrumb">
      <ol className="flex items-center space-x-2">
        {items.map((item, index) => (
          <li key={item.href} className="flex items-center">
            {index > 0 && (
              <ChevronRight className="h-4 w-4 text-gray-400 mx-2" />
            )}
            {index === items.length - 1 ? (
              <span className="text-sm font-medium text-gray-500">
                {item.label}
              </span>
            ) : (
              <Link
                href={item.href}
                className="text-sm font-medium text-gray-500 hover:text-gray-700"
              >
                {item.label}
              </Link>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
}
