// pages/auth/login.vue
<script setup lang="ts">
import Input from '@/components/ui/Input.vue'
import Label from '@/components/ui/Label.vue'
import Button from '@/components/ui/Button.vue'

const { login, user } = useAuth()
const loading = ref(false)
const errorMsg = ref<string | null>(null)
const email = ref('')
const password = ref('')
const router = useRouter()

watchEffect(() => {
  if (user.value) router.replace('/dashboard')
})

const onSubmit = async () => {
  errorMsg.value = null
  loading.value = true

  try {
    await login(email.value, password.value)
    router.replace('/dashboard')
  } catch (error: any) {
    errorMsg.value = error.message
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="flex min-h-screen items-center justify-center p-6">
    <form @submit.prevent="onSubmit" class="w-full max-w-sm space-y-4">
      <h1 class="text-xl font-semibold">Iniciar sesión</h1>
      <div>
        <Label>Email</Label>
        <Input v-model="email" type="email" placeholder="tu@correo.com" />
      </div>
      <div>
        <Label>Password</Label>
        <Input v-model="password" type="password" placeholder="********" />
      </div>
      <p v-if="errorMsg" class="text-sm text-red-600">{{ errorMsg }}</p>
      <Button :disabled="loading" class="w-full">
        {{ loading ? 'Ingresando…' : 'Ingresar' }}
      </Button>
      <p class="text-sm">
        ¿No tienes cuenta?
        <NuxtLink class="underline" to="/auth/register">Regístrate</NuxtLink>
      </p>
    </form>
  </div>
</template>

// app/auth/login/page.tsx
"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import Link from "next/link";
import { loginSchema } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAuth } from "@/hooks/use-auth";

export default function LoginPage() {
  const { login, loading } = useAuth();
  const [errorMessage, setErrorMessage] = useState("");

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(loginSchema),
  });

  async function onSubmit(data: any) {
    setErrorMessage("");
    const result = await login(data.email, data.password);

    if (result.error) {
      setErrorMessage(result.error);
    }
  }

  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Iniciar sesión
          </h2>
        </div>
        <form className="mt-8 space-y-6" onSubmit={handleSubmit(onSubmit)}>
          <div className="rounded-md shadow-sm space-y-4">
            <div>
              <Label htmlFor="email">Correo electrónico</Label>
              <Input
                id="email"
                type="email"
                {...register("email")}
                className={errors.email ? "border-red-500" : ""}
              />
              {errors.email && (
                <p className="mt-1 text-sm text-red-500">
                  {errors.email.message as string}
                </p>
              )}
            </div>

            <div>
              <Label htmlFor="password">Contraseña</Label>
              <Input
                id="password"
                type="password"
                {...register("password")}
                className={errors.password ? "border-red-500" : ""}
              />
              {errors.password && (
                <p className="mt-1 text-sm text-red-500">
                  {errors.password.message as string}
                </p>
              )}
            </div>
          </div>

          {errorMessage && (
            <p className="text-center text-red-500">{errorMessage}</p>
          )}

          <div>
            <Button type="submit" className="w-full" disabled={loading}>
              {loading ? "Iniciando sesión..." : "Iniciar sesión"}
            </Button>
          </div>
        </form>

        <p className="mt-2 text-center text-sm text-gray-600">
          ¿No tienes una cuenta?{" "}
          <Link
            href="/auth/register"
            className="font-medium text-blue-600 hover:text-blue-500"
          >
            Registrarse
          </Link>
        </p>
      </div>
    </div>
  );
}
